# -*- coding: utf-8 -*-
"""wine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvW_-l_I0xitd6E71mOuNsdh4PtjLsAB
"""

import numpy as np
import gradio as gr
import uvicorn

from fastapi import FastAPI
from pydantic import BaseModel, Field

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

wine = load_wine()
X_full = wine.data
y = wine.target
feature_names = wine.feature_names
target_names = wine.target_names

selected_features = ["flavanoids", "color_intensity", "proline"]
selected_indices = [feature_names.index(feature) for feature in selected_features]
X = X_full[:, selected_indices]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000, random_state=42))
])
model.fit(X_train, y_train)

app = FastAPI(
    title="Premium Wine Predictor API",
    description="Advanced Wine classification server using 3 key features",
    version="2.0"
)

class WineInput(BaseModel):
    flavanoids: float = Field(..., description="Flavanoids content", examples=[2.0])
    color_intensity: float = Field(..., description="Color intensity score", examples=[5.0])
    proline: float = Field(..., description="Proline concentration", examples=[750.0])

@app.get("/")
def root():
    return {
        "status": "online",
        "endpoints": {
            "web_ui": "/gradio",
            "api_docs": "/docs"
        }
    }

@app.post("/predict")
def predict_api(data: WineInput):
    input_data = np.array([[data.flavanoids, data.color_intensity, data.proline]])

    prediction_index = int(model.predict(input_data)[0])
    prediction_name = target_names[prediction_index]

    probabilities = model.predict_proba(input_data)[0]
    confidence = float(np.max(probabilities))

    return {
        "prediction": prediction_name,
        "class_index": prediction_index,
        "confidence": round(confidence, 4),
        "all_probabilities": {target_names[i]: round(float(prob), 4) for i, prob in enumerate(probabilities)}
    }


def predict_gradio(flavanoids, color_intensity, proline):
    input_data = np.array([[flavanoids, color_intensity, proline]])

    prediction_index = model.predict(input_data)[0]
    prediction_name = target_names[prediction_index]
    probabilities = model.predict_proba(input_data)[0]

    label_output = {target_names[i]: float(probabilities[i]) for i in range(len(target_names))}

    json_output = {
        "Selected Wine Class": prediction_name,
        "Model Confidence": f"{np.max(probabilities) * 100:.2f}%",
        "Input Summary": {
            "Flavanoids": flavanoids,
            "Color Intensity": color_intensity,
            "Proline": proline
        }
    }

    return label_output, json_output

with gr.Blocks(theme=gr.themes.Soft(), title="Wine Intelligence Center") as b_app:
    gr.Markdown(
        """
        # 🍷 Wine Intelligence Classifier
        입력하신 3가지 화학적 특성을 바탕으로 머신러닝 모델이 와인의 품종(Class 0, 1, 2)을 분석합니다.
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 📊 와인 성분 입력")
            in_flav = gr.Number(label="Flavanoids (플라보노이드)", value=2.03)
            in_color = gr.Number(label="Color Intensity (색상 강도)", value=5.06)
            in_pro = gr.Number(label="Proline (프롤린)", value=746.0)
            btn_submit = gr.Button("🔮 분석하기", variant="primary")

        with gr.Column(scale=1):
            gr.Markdown("### 🎯 예측 결과")
            out_label = gr.Label(label="분류 확률 (가장 높은 확률 기준)")
            out_json = gr.JSON(label="상세 분석 리포트")

    btn_submit.click(
        fn=predict_gradio,
        inputs=[in_flav, in_color, in_pro],
        outputs=[out_label, out_json]
    )

app = gr.mount_gradio_app(app, b_app, path="/gradio")

if __name__ == "__main__":
    b_app.launch(
        inline=True,
        share=False
    )