# -*- coding: utf-8 -*-
"""도서관

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGO2uMDcAYPbpDwBl1UjRSyFOX-ft-Sv
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile database.py
# 
# books_db = {
#    1: {"title": "파이썬 마스터", "author": "홍길동", "available": True},
#     2: {"title": "FastAPI로 배우는 웹 개발", "author": "이순신", "available": True},
#     3: {"title": "Gradio UI 가이드", "author": "김철수", "available": True},
#     4: {"title": "앱프로그래밍", "author": "김스키마", "available": True},
#     5: {"title": "데이터 관련 서적", "author": "DBMS", "available": True},
#     6: {"title": "게임의 이해", "author": "넥슨컴퍼니", "available": True},
#     7: {"title": "핸드폰은 갤럭시다", "author": "애플스튜디오", "available": True},
#     8: {"title": "앱등이의 하루", "author": "삼성주 오너", "available": True},
#     9: {"title": "밥보다는 빵이지", "author": "백반집사장", "available": True},
#     10: {"title": "멍 멍 멍", "author": "옆집 고양이", "available": True},
# }
# 
# rent_history = {
#     3: {"user": "접속자A", "date": "2026-05-28"}
# }
# 
# def get_all_books():
#     """전체 도서 데이터를 그대로 뽑아옴"""
#     return books_db
# 
# def get_all_history():
#     """전체 대여 이력 데이터를 그대로 뽑아옴"""
#     return rent_history
# 
# def update_book_status(book_id: int, available: bool):
#     """도서의 대여 가능 상태를 업데이트"""
#     if book_id in books_db:
#         books_db[book_id]["available"] = available
#         return True
#     return False
# 
# def add_rent_history(book_id: int, user: str, date: str):
#     """대여 이력 추가"""
#     rent_history[book_id] = {"user": user, "date": date}
# 
# def remove_rent_history(book_id: int):
#     """반납 시 대여 이력 삭제"""
#     if book_id in rent_history:
#         del rent_history[book_id]

# Commented out IPython magic to ensure Python compatibility.
# %%writefile borrow_manager.py
# 
# import database
# 
# def rent_book_service(book_id: int, user_name: str = "일반회원") -> dict:
#     """손님이 책을 빌리는 것을 인식하고 처리하는 메인 함수"""
#     books = database.get_all_books()
# 
#     if book_id not in books:
#         return {"success": False, "message": "❌ 존재하지 않는 도서 ID입니다."}
# 
#     if not books[book_id]["available"]:
#         return {"success": False, "message": "❌ 이미 다른 손님이 빌려간 책입니다."}
# 
# 
#     database.update_book_status(book_id, available=False)
#     database.add_rent_history(book_id, user=user_name, date="2026-05-29")
# 
#     return {"success": True, "message": f"🎉 '{books[book_id]['title']}' 대여 처리가 완료되었습니다!"}
# 
# def return_book_service(book_id: int) -> dict:
#     """손님이 책을 반납하는 것을 인식하고 처리하는 메인 함수"""
#     books = database.get_all_books()
# 
#     if book_id not in books:
#         return {"success": False, "message": "❌ 존재하지 않는 도서 ID입니다."}
# 
#     if books[book_id]["available"]:
#         return {"success": False, "message": "❌ 이미 반납 완료된 책입니다."}
# 
# 
#     database.update_book_status(book_id, available=True)
#     database.remove_rent_history(book_id)
# 
#     return {"success": True, "message": f"🔄 '{books[book_id]['title']}' 반납 처리가 완료되었습니다!"}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile analyzer.py
# 
# import database
# 
# def get_library_summary():
#     """대여된 책과 남은 책의 데이터를 파악하고 분석하여 반환"""
#     books = database.get_all_books()
#     history = database.get_all_history()
# 
#     total_books = len(books)
#     rented_books = total_books - sum(1 for b in books.values() if b["available"])
#     available_books = total_books - rented_books
#     rent_ratio = (rented_books / total_books) * 100 if total_books > 0 else 0
# 
# 
#     book_list_text = ""
#     for b_id, info in books.items():
#         status = "🟢 대여 가능" if info["available"] else "🔴 대여 중"
#         renter_info = f" (대여인: {history[b_id]['user']})" if b_id in history else ""
#         book_list_text += f"[{b_id}] {info['title']} - {info['author']} | {status}{renter_info}\n"
# 
#     analysis_result = {
#         "total": total_books,
#         "rented": rented_books,
#         "available": available_books,
#         "ratio": f"{rent_ratio:.1f}%",
#         "list_text": book_list_text
#     }
# 
#     return analysis_result

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# from fastapi import FastAPI
# import gradio as gr
# import borrow_manager
# import analyzer
# 
# app = FastAPI(title="도서 관리 통합 시스템")
# 
# def update_ui_view():
#     """데이터를 파악하는 모듈(analyzer)에서 최신 데이터를 가져와 UI를 갱신"""
#     data = analyzer.get_library_summary()
#     status_summary = f"📊 총 도서: {data['total']}권 | 대여 중: {data['rented']}권 | 대여 가능: {data['available']}권 (대여율: {data['ratio']})"
#     return data["list_text"], status_summary
# 
# def ui_handle_rent(book_id):
#     if book_id is None:
#         return "⚠️ 도서 ID를 입력해주세요.", *update_ui_view()
# 
#     # 메인 대여 로직 모듈 호출
#     result = borrow_manager.rent_book_service(int(book_id), user_name="홍길동 고객님")
#     list_text, summary_text = update_ui_view()
#     return result["message"], list_text, summary_text
# 
# def ui_handle_return(book_id):
#     if book_id is None:
#         return "⚠️ 도서 ID를 입력해주세요.", *update_ui_view()
# 
#     # 메인 반납 로직 모듈 호출
#     result = borrow_manager.return_book_service(int(book_id))
#     list_text, summary_text = update_ui_view()
#     return result["message"], list_text, summary_text
# 
# # --- Gradio UI 시각화 정의 ---
# init_list, init_summary = update_ui_view()
# 
# with gr.Blocks(title="도서관 책 대여 시스템") as demo:
#     gr.Markdown("# 📚 도서관 데이터 시각화 및 대여 시스템")
# 
#     # 상단 통계 바 (analyzer 모듈 결과물 시각화)
#     summary_viewer = gr.Textbox(value=init_summary, label="📊 실시간 도서관 대여 통계", interactive=False)
# 
#     with gr.Row():
#         # 왼쪽: 도서 현황 파악 리스트
#         with gr.Column():
#             gr.Markdown("### 📖 도서 보유 및 대여 현황")
#             book_list_viewer = gr.Textbox(value=init_list, label="도서 목록", lines=10, interactive=False)
#             refresh_btn = gr.Button("🔄 현황 새로고침")
# 
#         # 오른쪽: 대여/반납 메인 인터페이스
#         with gr.Column():
#             gr.Markdown("### ⚡ 대여 / 반납 키오스크")
#             book_id_input = gr.Number(label="대여/반납할 도서 ID 입력 (숫자)", precision=0)
# 
#             with gr.Row():
#                 rent_btn = gr.Button("🔑 대여하기", variant="primary")
#                 return_btn = gr.Button("↩️ 반납하기")
# 
#             result_output = gr.Markdown(value="**안내:** 원하는 도서 ID를 입력하고 버튼을 눌러주세요.")
# 
#     # 이벤트 연결
#     refresh_btn.click(fn=update_ui_view, inputs=[], outputs=[book_list_viewer, summary_viewer])
#     rent_btn.click(fn=ui_handle_rent, inputs=[book_id_input], outputs=[result_output, book_list_viewer, summary_viewer])
#     return_btn.click(fn=ui_handle_return, inputs=[book_id_input], outputs=[result_output, book_list_viewer, summary_viewer])
# 
# # --- FastAPI에 Gradio 마운트 ---
# app = gr.mount_gradio_app(app, demo, path="/ui")

!pip install nest_asyncio uvicorn

import nest_asyncio
import uvicorn

nest_asyncio.apply()

# 4번 파일(app.py)의 app 객체를 uvicorn으로 구동
# 코랩 환경이므로 inline으로 Gradio를 띄우기 위해 아래처럼 실행해
import app
app.demo.launch(share=True)